version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "villaData"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-f9z92q7pr0wt"
s3_prefix = "villaData"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
