AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  villaData

  Sample SAM Template for villaData

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PandasFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: pandasFunction
      CodeUri: pandasFunction/
      Handler: app.lambda_handler
      Runtime: python3.8

